- updated for 2.5.0
Changed files:
    audacious-plugins-libdir.patch -> 1.2
    audacious-plugins-verbose_make.patch -> 1.2

diff --git a/audacious-plugins-verbose_make.patch b/audacious-plugins-verbose_make.patch
--- a/audacious-plugins-verbose_make.patch
+++ b/audacious-plugins-verbose_make.patch
@@ -1,45 +1,57 @@
---- buildsys.mk.in.orig	2011-02-07 19:20:48.661369541 +0000
-+++ buildsys.mk.in	2011-02-07 19:21:59.930520847 +0000
-@@ -92,7 +92,6 @@
+--- audacious-plugins-2.5.0/buildsys.mk.in~	2011-04-16 18:10:09.000000000 +0200
++++ audacious-plugins-2.5.0/buildsys.mk.in	2011-05-04 13:15:04.393333839 +0200
+@@ -93,7 +93,6 @@
  
  MO_FILES = ${LOCALES:.po=.mo}
  
 -.SILENT:
  .SUFFIXES:
- .SUFFIXES: .beam .c .cc .cxx .d .dep .erl .mo .m .mm .o .po .py .pyc .xpm .S
- .PHONY: all subdirs pre-depend depend install install-extra uninstall uninstall-extra clean distclean
-@@ -502,21 +501,21 @@
- 	# ./configure creates .deps files even in folders not listed in SUBDIRS.
- 	rm -f `find . -name .deps ! -path ./.hg\*`
+ .SUFFIXES: .beam .c .c.dep .cc .cc.dep .cxx .cxx.dep .d .erl .lib.o .mo .m .m.dep .mm .mm.dep .o .plugin.o .po .py .pyc .xpm .S .S.dep
+ .PHONY: all subdirs pre-depend depend install install-extra uninstall uninstall-extra clean distclean locales
+@@ -564,27 +563,27 @@
+ 		fi \
+ 	done
  
--DIR_ENTER = printf "\033[K\033[0;36mEntering directory \033[1;36m$$i\033[0;36m.\033[0m\n"; cd $$i || exit 1
--DIR_LEAVE = printf "\033[K\033[0;36mLeaving directory \033[1;36m$$i\033[0;36m.\033[0m\n"; cd .. || exit 1
--DEPEND_STATUS = printf "\033[K\033[0;33mGenerating dependencies...\033[0m\r"
--DEPEND_OK = printf "\033[K\033[0;32mSuccessfully generated dependencies.\033[0m\n"
--DEPEND_FAILED = printf "\033[K\033[0;31mFailed to generate dependencies!\033[0m\n"; exit 1
--COMPILE_STATUS = printf "\033[K\033[0;33mCompiling \033[1;33m$<\033[0;33m...\033[0m\r"
--COMPILE_OK = printf "\033[K\033[0;32mSuccessfully compiled \033[1;32m$<\033[0;32m.\033[0m\n"
--COMPILE_FAILED = printf "\033[K\033[0;31mFailed to compile \033[1;31m$<\033[0;31m!\033[0m\n"; exit 1
--LINK_STATUS = printf "\033[K\033[0;33mLinking \033[1;33m$@\033[0;33m...\033[0m\r"
--LINK_OK = printf "\033[K\033[0;32mSuccessfully linked \033[1;32m$@\033[0;32m.\033[0m\n"
--LINK_FAILED = printf "\033[K\033[0;31mFailed to link \033[1;31m$@\033[0;31m!\033[0m\n"; exit 1
--INSTALL_STATUS = printf "\033[K\033[0;33mInstalling \033[1;33m$$i\033[0;33m...\033[0m\r"
--INSTALL_OK = printf "\033[K\033[0;32mSuccessfully installed \033[1;32m$$i\033[0;32m.\033[0m\n"
--INSTALL_FAILED = printf "\033[K\033[0;31mFailed to install \033[1;31m$$i\033[0;31m!\033[0m\n"; exit 1
--DELETE_OK = printf "\033[K\033[0;34mDeleted \033[1;34m$$i\033[0;34m.\033[0m\n"
--DELETE_FAILED = printf "\033[K\033[0;31mFailed to delete \033[1;31m$$i\033[0;31m!\033[0m\n"; exit 1
+-DIR_ENTER = printf "@TERM_EL@@TERM_SETAF6@Entering directory @TERM_BOLD@$$i@TERM_SGR0@@TERM_SETAF6@.@TERM_SGR0@\n"; cd $$i || exit 1
+-DIR_LEAVE = printf "@TERM_EL@@TERM_SETAF6@Leaving directory @TERM_BOLD@$$i@TERM_SGR0@@TERM_SETAF6@.@TERM_SGR0@\n"; cd .. || exit 1
+-DEPEND_STATUS = printf "@TERM_EL@@TERM_SETAF3@Generating dependencies...@TERM_SGR0@\r"
+-DEPEND_OK = printf "@TERM_EL@@TERM_SETAF2@Successfully generated dependencies.@TERM_SGR0@\n"
+-DEPEND_FAILED = printf "@TERM_EL@@TERM_SETAF1@Failed to generate dependencies!@TERM_SGR0@\n"; exit 1
+-COMPILE_STATUS = printf "@TERM_EL@@TERM_SETAF3@Compiling @TERM_BOLD@$<@TERM_SGR0@@TERM_SETAF3@...@TERM_SGR0@\r"
+-COMPILE_OK = printf "@TERM_EL@@TERM_SETAF2@Successfully compiled @TERM_BOLD@$<@TERM_SGR0@@TERM_SETAF2@.@TERM_SGR0@\n"
+-COMPILE_FAILED = printf "@TERM_EL@@TERM_SETAF1@Failed to compile @TERM_BOLD@$<@TERM_SGR0@@TERM_SETAF1@!@TERM_SGR0@\n"; exit 1
+-COMPILE_LIB_STATUS = printf "@TERM_EL@@TERM_SETAF3@Compiling @TERM_BOLD@$<@TERM_SGR0@@TERM_SETAF3@ (lib)...@TERM_SGR0@\r"
+-COMPILE_LIB_OK = printf "@TERM_EL@@TERM_SETAF2@Successfully compiled @TERM_BOLD@$<@TERM_SGR0@@TERM_SETAF2@ (lib).@TERM_SGR0@\n"
+-COMPILE_LIB_FAILED = printf "@TERM_EL@@TERM_SETAF1@Failed to compile @TERM_BOLD@$<@TERM_SGR0@@TERM_SETAF1@ (lib)!@TERM_SGR0@\n"; exit 1
+-COMPILE_PLUGIN_STATUS = printf "@TERM_EL@@TERM_SETAF3@Compiling @TERM_BOLD@$<@TERM_SGR0@@TERM_SETAF3@ (plugin)...@TERM_SGR0@\r"
+-COMPILE_PLUGIN_OK = printf "@TERM_EL@@TERM_SETAF2@Successfully compiled @TERM_BOLD@$<@TERM_SGR0@@TERM_SETAF2@ (plugin).@TERM_SGR0@\n"
+-COMPILE_PLUGIN_FAILED = printf "@TERM_EL@@TERM_SETAF1@Failed to compile @TERM_BOLD@$<@TERM_SGR0@@TERM_SETAF1@ (plugin)!@TERM_SGR0@\n"; exit 1
+-LINK_STATUS = printf "@TERM_EL@@TERM_SETAF3@Linking @TERM_BOLD@$@@TERM_SGR0@@TERM_SETAF3@...@TERM_SGR0@\r"
+-LINK_OK = printf "@TERM_EL@@TERM_SETAF2@Successfully linked @TERM_BOLD@$@@TERM_SGR0@@TERM_SETAF2@.@TERM_SGR0@\n"
+-LINK_FAILED = printf "@TERM_EL@@TERM_SETAF1@Failed to link @TERM_BOLD@$@@TERM_SGR0@@TERM_SETAF1@!@TERM_SGR0@\n"; exit 1
+-INSTALL_STATUS = printf "@TERM_EL@@TERM_SETAF3@Installing @TERM_BOLD@$$i@TERM_SGR0@@TERM_SETAF3@...@TERM_SGR0@\r"
+-INSTALL_OK = printf "@TERM_EL@@TERM_SETAF2@Successfully installed @TERM_BOLD@$$i@TERM_SGR0@@TERM_SETAF2@.@TERM_SGR0@\n"
+-INSTALL_FAILED = printf "@TERM_EL@@TERM_SETAF1@Failed to install @TERM_BOLD@$$i@TERM_SGR0@@TERM_SETAF1@!@TERM_SGR0@\n"; exit 1
+-DELETE_OK = printf "@TERM_EL@@TERM_SETAF4@Deleted @TERM_BOLD@$$i@TERM_SGR0@@TERM_SETAF4@.@TERM_SGR0@\n"
+-DELETE_FAILED = printf "@TERM_EL@@TERM_SETAF1@Failed to delete @TERM_BOLD@$$i@TERM_SGR0@@TERM_SETAF1@!@TERM_SGR0@\n"; exit 1
 +DIR_ENTER = printf "Entering directory $$i.\n"; cd $$i || exit 1
 +DIR_LEAVE = printf "Leaving directory $$i.\n"; cd .. || exit 1
-+DEPEND_STATUS = printf "Generating dependencies...\n"
++DEPEND_STATUS = printf "Generating dependencies...\r"
 +DEPEND_OK = printf "Successfully generated dependencies.\n"
 +DEPEND_FAILED = printf "Failed to generate dependencies!\n"; exit 1
-+COMPILE_STATUS = printf "Compiling $<...\n"
++COMPILE_STATUS = printf "Compiling $<...\r"
 +COMPILE_OK = printf "Successfully compiled $<.\n"
 +COMPILE_FAILED = printf "Failed to compile $<!\n"; exit 1
-+LINK_STATUS = printf "Linking $@...\n"
++COMPILE_LIB_STATUS = printf "Compiling $< (lib)...\r"
++COMPILE_LIB_OK = printf "Successfully compiled $< (lib).\n"
++COMPILE_LIB_FAILED = printf "Failed to compile $< (lib)!\n"; exit 1
++COMPILE_PLUGIN_STATUS = printf "Compiling $< (plugin)...\r"
++COMPILE_PLUGIN_OK = printf "Successfully compiled $< (plugin).\n"
++COMPILE_PLUGIN_FAILED = printf "Failed to compile $< (plugin)!\n"; exit 1
++LINK_STATUS = printf "Linking $@...\r"
 +LINK_OK = printf "Successfully linked $@.\n"
 +LINK_FAILED = printf "Failed to link $@!\n"; exit 1
-+INSTALL_STATUS = printf "Installing $$i...\n"
++INSTALL_STATUS = printf "Installing $$i...\r"
 +INSTALL_OK = printf "Successfully installed $$i.\n"
 +INSTALL_FAILED = printf "Failed to install $$i!\n"; exit 1
 +DELETE_OK = printf "Deleted $$i.\n"
